name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]

    steps:
    - name: Download source files
      uses: actions/checkout@v2
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Setup environment
      run: |
        if test $(uname -s) != "Darwin" ;
        then
          sudo apt-get update -q
          sudo apt-get -yq install locate libx11-dev libxext-dev libxpm-dev
          echo -e "\nHeaders locations :"
          locate Xlib.h
          file /usr/include/X11/extensions/XShm.h
          locate XShm.h
          echo "Done"
        fi
    - name: Compile
      run: make
    - name: Clean
      run: make fclean
